name: Test

on: [push, pull_request]

jobs:
  test:
    name: Create test site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # middleman init wants to clone the repo, so we need full history

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: ./create-test-site.sh
